homework n.9
nvbach91/4IZ268-2020-2021-ZS pull request #102
Opened 2020-11-26 22:10 UTC by madkhab

https://eso.vse.cz/~kham06/cv09/homework

2020-11-26 23:25 UTC, nvbach91 approved these changes, later dismissed

2020-11-26 23:25 UTC, nvbach91 commented on www/cv09/homework/main.js
> +const CipherTextPlace = document.querySelector('#inputcipher');
prosim pouzit camelCase...

2020-11-26 23:25 UTC, nvbach91 commented on www/cv09/homework/main.js
> +        Table.insertBefore(impossible, DecipherButton);
co je to impossible?

2020-11-26 23:25 UTC, nvbach91 commented on www/cv09/homework/main.js
> +        };
tady nema byt strednik

2020-11-26 23:25 UTC, nvbach91 commented on www/cv09/homework/main.js
> +    for ( i = 0; i < str.length; i++){
`for (let i`

2020-11-26 23:25 UTC, nvbach91 commented on www/cv09/homework/main.js
> +    return array.indexOf(value) > -1;
camelCase, jinak existuje funkce `array.includes()`

2020-11-26 23:26 UTC, nvbach91 requested changes
chybi vam slozka `kham06` mezi `www` a `cv09`, odevzdejte ukol znovu

2020-12-03 12:30 UTC, nvbach91 commented
@madkhab budete to opravovat?

2020-12-03 13:53 UTC, madkhab commented
Moc se omlouvám, neviděl jsem této zprávy. Do zítřka do upravím.

2020-12-04 09:01 UTC, madkhab commented
Dobrý den. Bohužel, nedokázal jsem přidat funkce camelCase, protože moc ji používat neumím.

2020-12-04 12:06 UTC, nvbach91 commented
camelCase neni funkce, to je zpusob pojmenovani nayvu promennych, viz 8. cviceni

2020-12-06 17:01 UTC, closed without merging