potp04-hw10
nvbach91/4IZ268-2020-2021-ZS pull request #119
Opened 2020-12-02 19:52 UTC by petrpotmesil

Odevzdávám hw10

2020-12-03 10:40 UTC, nvbach91 commented
a jaký odkaz k vyzkoušení?

2020-12-03 17:29 UTC, petrpotmesil commented
Omlouvám se, zapomněl jsem přiložit.
https://eso.vse.cz/~potp04/cv10/homework/

2020-12-06 17:08 UTC, nvbach91 requested changes
odevzdat musite celou slozku `/www/potp04/hw10` podle navodu

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +var CityName = "";
prosim pouzit camelCase,

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +  document.getElementById("game-field").appendChild(div); //div se přidá
- vyber kontejneru provedte mimo cyklu,
- aktualizace DOMu provedte mimo cyklu

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +  div.setAttribute("onClick", "divClicked(this.id)"); //když je na div kluknuto, spustí se mi funkce a předávám id
tohle neni spravny zpusob pripojeni posluchace udalosti

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +  div.setAttribute("class", "card");
`div.classList.add()`

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +  if (clear == true) {
`if (clear)`

2020-12-06 17:08 UTC, nvbach91 commented on homework/js/main.js
> +      document.getElementById("points").innerHTML = "Your points: " + points; //vypsání pointů
- `document.querySelector()`
- vyber elementu z DOMu pouze jednou mimo funkce kde se pouziva

2020-12-15 11:02 UTC, closed without merging