novb12-hw10
nvbach91/4IZ268-2020-2021-ZS pull request #126
Opened 2020-12-03 17:06 UTC by bnaru

https://eso.vse.cz/~novb12/cv10/homework/

2020-12-06 17:22 UTC, nvbach91 requested changes
ukol musite odevzdat jako celou slozku `/www/novb12/hw10` podle navodu

2020-12-06 17:22 UTC, nvbach91 commented on js/main.js
> +// přidání karet pomocí DOM - přidává pouze po jedné, nejsem si jistá, jak to použít pro rovnou zdvojnení - nefunguje mi to znovu pro concat, ani jinými způsoby - stejně tak mi nefungovalo bez zásahu
restart hry by spocivalo v tom vsechno dat do puvodniho stavu a spustit stejny kod znova, takze muzete na tohle to vsechno vytvorit funkci napr. `initializeGame()` a pak ji zavolat ve funkci `resetGame()`, ktera predtim dela to vycisteni

```js
const resetGame = () => {
    // vycistit game field
    // zamichat karty
    // resetovat body a promenne
    // inicializovat hru
};
```

2020-12-06 17:22 UTC, nvbach91 commented on js/main.js
> +  gameField.appendChild(card);
aktualizaci DOMu provedme mimo cyklu
```js
const newCards = [];
cities.forEach((city) => {
     const newCard = createCard();
     newCards.push(newCard);
});
field.append(...newCards);
```

2020-12-06 17:22 UTC, nvbach91 commented on js/main.js
> +let playingCard = function (card) {
pouzivejte arrow funkce

2020-12-06 17:24 UTC, nvbach91 commented on js/main.js
> +    playersPoints = score.innerText;
nema tohle byt naopak? do ceho dosazujete?

2020-12-07 11:20 UTC, bnaru commented
> ukol musite odevzdat jako celou slozku `/www/novb12/hw10` podle navodu

Pardon, to jsem si nějak neuvědomila. Nevíte náhodou, jestli nyní musím vytvořit nový Pull request nebo to lze nějak snadno opravit? Snažila jsem se na to přijít, abych jen provedla úpravu, avšak byla jsem neúspěšná.

2020-12-08 23:08 UTC, nvbach91 commented
je to v navodu, ale jednodussi pro vas by bylo vytvorit si novy pull request, potom ho zminujte zde #126

2020-12-08 23:11 UTC, nvbach91 commented
aha tak to bylo #147 ok vyborne

2020-12-08 23:11 UTC, closed without merging