fral06-hw10
nvbach91/4IZ268-2020-2021-ZS pull request #127
Opened 2020-12-03 19:08 UTC by l-k-sfr-jt

2020-12-06 17:26 UTC, nvbach91 requested changes

2020-12-06 17:26 UTC, nvbach91 commented on www/fral06/hw10/js/main.js
> +let teams = [{team: 'Borussia Dortmund', id: 'bvb'}, {team: 'Lazio Rome', id: 'laz'}, {team: 'FC Zenit', id: 'zen'},
tohle by se dalo naformatovat

2020-12-06 17:26 UTC, nvbach91 commented on www/fral06/hw10/js/main.js
> +const pointsElement = document.getElementById('points');
lepsi `querySelector`

2020-12-06 17:27 UTC, nvbach91 reviewed
jeste bych potreboval odkaz na vase reseni k vyzkouseni

2020-12-10 17:17 UTC, l-k-sfr-jt commented
https://eso.vse.cz/~fral06/hw10/

2020-12-10 23:18 UTC, nvbach91 approved these changes

2020-12-10 23:19 UTC, merged