podj00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #174
Opened 2020-12-16 09:15 UTC by jpodestat

Web dostupný na: https://eso.vse.cz/~podj00/sp2/

2021-01-11 21:03 UTC, jpodestat commented
Chtěl bych jen vysvětlit, proč mám ty responses namockované. Volané api po nějaké době začne padat na 429 - Too Many Requests. Bohužel se to stává časteji, než píšou na webu (údajný limit 60 volání hod) a měnit api na poslední chvíli (zvlášť, když už jsem měl celou stránku hotovou), mi přišlo nešťastné. Doufám, že při případném výpadku nebude problém, že bych ta data bral z těch jsonů. Volání jinak fungují, netuším jen jak dlouho...

2021-01-15 01:02 UTC, nvbach91 requested changes
- pridejte moznost ukladani zemi do seznamu casto sledovanych pro rychlejsi pristup k datum (na jedno kliknuti)

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +        //only 1 input (clicked one) can be checked
tak na to se hodi napr radio button ne?

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/index.html
> +                <input placeholder="Vyberte zemi!" type="text" id="country" name="fname">
tady je vhodny pouzit `<select>` se vsemi validnimi nazvy zemi (vygenerovat z dat)

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +        const country = $('#country');
elementy z html vybrat predem, ne behem pouziti

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +                return 1
`;` chybi na docela hodne mistech

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +            let newCanvas = $('<canvas id="one-country" width="3000" height="600"></canvas>');
lepsi sirku nechat responzivni podle sirky stranky

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/index.html
> +                <input id="select" type="button" value="Zobrazit">
pouzivejte `<button>`

2021-01-15 01:02 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +    selectButton.click((e) => {
udelejte prevenci vicenasobneho kliknuti na toto tlacitko (muze byt napr. animace v tlacitku, a behem nacitani zakazat kliknuti, a po skonceni volani ajaxu to zmenit zpatky do puvodniho stavu)

2021-01-15 21:12 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-15 21:12 UTC, nvbach91 commented on www/podj00/sp2/assets/js/main.js
> +        $('input[type="radio"]').not(e.currentTarget).prop('checked', false);
tady jste asi nepochopil, to ze ma byt vybrana pouze jedna moznost je defaultni chovani radio buttonu, takze neni potreba implementovat udalost change..

2021-01-15 21:13 UTC, merged