pfej00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #185
Opened 2020-12-17 17:33 UTC by pfej00

Aplikaci plánuji nasadit na Heroku, jelikož se jedná o react.

2020-12-20 23:14 UTC, nvbach91 requested changes
přečtěte si znovu návod na odevzdávání SP2 přes GitHub, zejména u sekce ohledně struktury složek `/www/xname/sp2` a založte nový Pull Request

2020-12-28 22:20 UTC, pfej00 commented
@nvbach91 Změnil jsem soubory projektu podle vašich požadavků a nahrál je do této větve.

2020-12-29 16:13 UTC, nvbach91 commented
@pfej00 stále nevidím správnou strukturu složek

2020-12-29 16:41 UTC, pfej00 commented
@nvbach91, možná jsem slepej, ale nevidím možnou  chybu. Prosim o vysvětlení.
Díky za odpověď.

![obrazek](https://user-images.githubusercontent.com/72281944/103299098-14885f80-49fc-11eb-9846-02233773c17c.png)

![obrazek](https://user-images.githubusercontent.com/72281944/103299229-56b1a100-49fc-11eb-989e-b1fa52ca9e4c.png)

2020-12-29 16:47 UTC, nvbach91 commented
podívejte se do "Files changed", u všech položek by mělo být `/www/pfej00/sp2/...`, což není a jsou tam změny i u souborů jiných studentů. Doporučuji vytvoření nového Pull Requestu, kam nahrajete pouze svoji složku

2020-12-29 19:24 UTC, closed without merging