duzm00 sp2
nvbach91/4IZ268-2020-2021-ZS pull request #187
Opened 2020-12-18 11:53 UTC by Duzij

https://fastguess.azurewebsites.net/

2021-01-07 22:07 UTC, nvbach91 commented
aplikace neni dostupna

2021-01-07 22:14 UTC, Duzij commented
Ano, stopnul jsem jí, jelikož jsem nechtěl aby byla veřejně přístupná. Už by měla běžet :)

2021-01-07 22:50 UTC, nvbach91 requested changes
Ukoly:
- vsechny stranky nacist bez reloadu stranky
- naslouchat keyboard event pro hrani na klavesnici (zadavani hodnoty odpovedi)
- zobrazit score na finalnim screenu, vypocet
- kdyz zadam `https://fastguess.azurewebsites.net/score/new` a submit tak jsem v zebricku?
- zapamatovat si nickname hrace
- zvyraznit nickname aktualniho hrace v zebricku
- opravit loading spinner
- upozornit na nevalidni vstupy (score submission) nebo osetrit uzivatelske vstupy
- zobrazit cas hrani v scoreboardu
- zobrazit statistiku skore hrani (graf - jak se zlepsuju)

2021-01-08 11:10 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-08 11:11 UTC, merged