stey04 sp2
nvbach91/4IZ268-2020-2021-ZS pull request #191
Opened 2020-12-19 22:41 UTC by steepp

https://eso.vse.cz/~stey04/sp2/

2021-01-07 23:04 UTC, nvbach91 requested changes
Ukoly:
- zvetsit mapu na celou obrazovku
- umistit ovladani do leveho panelu
-

2021-01-07 23:04 UTC, nvbach91 commented on www/stey04/sp2/js/main.js
> +    }).then(() => sp1.detach());
chybi `catch`

2021-01-07 23:04 UTC, nvbach91 commented on www/stey04/sp2/js/main.js
> +    $.ajax('https://api.wheretheiss.at/v1/satellites/25544')
co kdyz bude tech satelitu vice?

2021-01-07 23:04 UTC, nvbach91 commented on www/stey04/sp2/js/main.js
> +const mapboxURL = 'https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw';
vsechen kod hodit do closure napr. `$(document).ready(() => { ... })`

2021-01-07 23:04 UTC, nvbach91 commented on www/stey04/sp2/js/main.js
> +    map.panTo([lat, long], animate = true);
zobrazujte i aktualizujte data ohledke lokace, rychlost, stanice

2021-01-08 21:21 UTC, steepp commented on www/stey04/sp2/js/main.js
> +    $.ajax('https://api.wheretheiss.at/v1/satellites/25544')
Je tam jen jeden.

2021-01-08 23:16 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-08 23:17 UTC, merged