prod10-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #194
Opened 2020-12-20 11:16 UTC by david-prochazka

Link to application: https://eso.vse.cz/~prod10/sp2/

2021-01-07 20:14 UTC, nvbach91 requested changes
musite vytvorit novy PR se semestralkou ve slozce `/www/prod10/sp2`

2021-01-07 20:14 UTC, nvbach91 commented on sp2/assets/js/main.js
> +    var ingredients = '';
let/const

2021-01-07 20:14 UTC, nvbach91 commented on sp2/assets/js/main.js
> +        spinner.appendTo($('#load-button'));
`loadButton`

2021-01-08 07:53 UTC, david-prochazka commented
Jak to prosím myslíte? Nerozumím tomu, myslel jsem, že jsem to tak dělal. Postupoval jsem podle návodu.

2021-01-08 14:25 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-08 14:25 UTC, merged