dinv00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #197
Opened 2020-12-20 12:05 UTC by dinv00

Link: https://eso.vse.cz/~dinv00/sp2/

2021-01-22 03:07 UTC, nvbach91 requested changes
- save ingredients - ja bych je chtel spis zobrazit nez stahovat, zobrazte to v dialogove okne (treba pomoci bootstrapu nebo alertify)
- more results button - nesmite davat do parametru to cislo ktere je vetsi nez hodnota `count` v odpovedi
- chybi podminka pouziti Browser API (napr. localStorage, location, history, ...) takze pouzijte treba localStorage na ukladani oblibenych receptu

2021-01-22 03:07 UTC, nvbach91 commented on www/dinv00/sp2/assets/js/FileSaver.js
> +/*
na ukladani textoveho souboru je tato knihovna overkill

2021-01-22 03:07 UTC, nvbach91 commented on www/dinv00/sp2/assets/js/main.js
> +    $("#loader").show();
elementy z HTML vybirejte predem, ne behem pouziti

2021-01-22 03:07 UTC, nvbach91 commented on www/dinv00/sp2/assets/js/main.js
> +    query = $("#search-text").val().trim().replaceAll(/\s+/g, "+");
elementy z HTML vybirejte predem, ne behem pouziti

2021-01-22 03:07 UTC, nvbach91 commented on www/dinv00/sp2/index.html
> +            <div class="search-bar">
tady ma byt formular

2021-01-22 03:07 UTC, nvbach91 commented on www/dinv00/sp2/assets/js/main.js
> +  $("#search").on("click", function () {
tady ma byt formular on submit

2021-01-22 10:58 UTC, dinv00 commented on www/dinv00/sp2/assets/js/main.js
> +    $("#loader").show();
```js
var func = () => {
  $('#submit-button').click();
};
```

```js
var submitButton = $('#submit-buton');
var func = () => {
  submitButton.click();
};
```

2021-01-27 10:26 UTC, nvbach91 approved these changes

2021-01-27 10:26 UTC, merged