ngut37-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #213
Opened 2020-12-20 19:17 UTC by ngut37

https://eso.vse.cz/~ngut37/sp2/

2021-01-14 23:51 UTC, nvbach91 requested changes
- nevim jak tuto aplikaci pouzit
- sjednotte ty 3 page do single page
- zmensit obrazek...
- dalsi postup az na zkousce...

2021-01-14 23:51 UTC, nvbach91 commented on www/ngut37/sp02/src/components/about/about.tsx
> +    <div className='aboutWrapper'>
`"`

2021-01-14 23:51 UTC, nvbach91 commented on www/ngut37/sp02/src/app.tsx
> +    <Router>
proc se vase aplikace refreshuje kdyz kliknu na navigaci?

2021-01-14 23:51 UTC, nvbach91 commented on www/ngut37/sp02/src/components/navbar/navbar.tsx
> +        <a href="./list">Find your path</a>
aha

2021-01-14 23:51 UTC, nvbach91 commented on www/ngut37/sp02/src/components/footer/footer.tsx
> +      <span><a href="https://github.com/ngut37">@ngut37</a></span>
`target="?"`

2021-01-15 14:03 UTC, ngut37 commented on www/ngut37/sp02/src/components/about/about.tsx
> +    <div className='aboutWrapper'>
Opraveno

2021-01-15 14:03 UTC, ngut37 commented on www/ngut37/sp02/src/app.tsx
> +    <Router>
Opraveno pomoci komponenty `<Link>`

2021-01-15 14:03 UTC, ngut37 commented on www/ngut37/sp02/src/components/navbar/navbar.tsx
> +        <a href="./list">Find your path</a>
Viz komentar nahore

2021-01-15 14:05 UTC, ngut37 commented on www/ngut37/sp02/src/components/footer/footer.tsx
> +      <span><a href="https://github.com/ngut37">@ngut37</a></span>
Opraveno

2021-01-15 14:11 UTC, ngut37 commented
Redeploy na https://sp-02.herokuapp.com/

- [ ] URL preview - implementovan, misto `onChange` jsem to dal `onBlur`, aby to nebombardovalo backend pri kazde zmene (deploynul jsem novou featuru z backendoveho repozitare)
- [ ] localStorage - zaznam se uklada do `localStorage` kdyz uzivatel clickne na **Create Link**, pokud pod stejny namepath napise jine heslo, tak se tomu zaznamu prepise (tzn. nevytvari se novy zaznam se stejnym namespace)
- [ ] drobne stylove upravy a odstraneni obrazku

2021-01-15 20:55 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-15 20:55 UTC, merged