🎉 Init base project
nvbach91/4IZ268-2020-2021-ZS pull request #224
Opened 2020-12-20 22:52 UTC by dmitrijt9

- play/pause audio
- visualize audio

2021-01-06 18:11 UTC, dmitrijt9 commented
Po domluve, nove zadani - aplikace pro vyhledavani a spravu knih napojenou na Google Books API.
Je to final pred obhajobou.

Jen duplikuji puvodni repo: https://github.com/dmitrijt9/bookcaser

Nasazuji na github pages na vlastni domenu: https://bookcaser.dasher.cz - pohodlnejsi kvuli nastavovani baseUrl ke statickym souborum a nemusim nahravat pres ftp :)

Z https://eso.vse.cz/~tkad06/sp2 se deje redirect na https://bookcaser.dasher.cz

2021-01-07 21:56 UTC, nvbach91 requested changes
Ukoly:
- click na knihu
- automaticke login kdyz je prihlaseny v google
- tooltip na tlacitka
- cachovani odpovedi z API kdyz dokud se neprovede destruktivni operace
- nabindovat stav umisteni knihy v policich pri pridavani na police

2021-01-08 10:35 UTC, dmitrijt9 commented
Zapracoval jsem vetsinu ukolu. Takovyhle je aktualni stav:

- [x] click na knihu
- [x] automaticke login kdyz je prihlaseny v google
- [x] tooltip na tlacitka
- [ ] cachovani odpovedi z API kdyz dokud se neprovede destruktivni operace
- [x] nabindovat stav umisteni knihy v policich pri pridavani na police

Pokud je to v poradku, tak bych rad takto uzavrel k hodnoceni :) 
Diky

2021-01-08 23:09 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-08 23:09 UTC, merged