sikj01-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #231
Opened 2020-12-21 08:45 UTC by sikj01

Link to application: https://eso.vse.cz/~sikj01/sp2/

2021-02-04 00:08 UTC, sikj01 commented
Omlouvám se za zmatek, nakonec se mi to podařilo nahrát správně sem.

2021-02-05 00:37 UTC, nvbach91 requested changes

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +        $("#main").html(`
elementy z HTML vybirat predem, ne behem pouziti

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +    var moviesGenres = {}
stredniky

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +            `<tr> <td colspan="5">
naformatovat

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +                url: `https://api.themoviedb.org/3/search/movie?api_key=a0c2b64a6fafee6976844c7c2cf29a7a&language=en-US&query=${searchQuery}&page=1&include_adult=false`,
baseURL, key parametr dat do promennych

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +                        var toWatch = getWatchlistItems()
stredniky

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +        return JSON.parse(window.localStorage.getItem("Watchlist")) || [];
try/catch

2021-02-05 00:37 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +                        <div class="input-group mb-3">
tady pouzivejte formular

2021-02-05 14:25 UTC, nvbach91 approved these changes

2021-02-05 14:25 UTC, merged