vecs00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #235
Opened 2020-12-27 20:28 UTC by vecs00

https://eso.vse.cz/~vecs00/sp2/

2021-01-14 20:14 UTC, nvbach91 requested changes
Ukoly:
- sjednotit vsechny 3 moduly (index, favorites, movie)
- osetrit uzivatelsky vstup
- pridat strankovani nebo nacist vice filmu a zobrazit je pod aktualnimi vysledky dokud nebudou zobrazeny vsechny vysledky

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/css/bootstrap.min.css
> +/*!
bootstrap naimportujte pres CDN

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +        $(".loading").removeClass("hide");
apostrof

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +            document.getElementById(`favorite-${favoriteImdbID}`).innerHTML = 'Přidat do oblíbených';
pouzit jQuery

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/movie.html
> +            getMovie();
presunout do main.js

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/movie.html
> +        <script src="js/main.js"></script>
main.js bude v poslednim script tagu

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +                            <a onclick="movieSelected('${movie.imdbID}')" class="btn btn-primary movie-card-button" href="#">Detail filmu</a>
tady nema byt onclick, jednalo by se o inline js

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +                $('#favorite').append(output);
elementy z html vybrat jednou na zacatku programu

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +                <img src="${movie.Poster}">
opravte rozmery obrazku, navic tohle neni validni html

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +               <a onclick="movieSelected('${movie.imdbID}')" class="btn btn-primary movie-card-button" href="#">Detail filmu</a>
odstrante vsechny inline js

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +        let searchText = $('#searchText').val();
elementy z html vybrat predem a ne behem pouziti

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +       <div class="movie-detail">
naformatovat kod

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +    let favoriteMovies = JSON.parse(localStorage.getItem("favoriteMovies"));
tady je dobre mit try/catch

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +    $('#favorite');
?

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/index.html
> +                    <a class="navbra-brand" href="favorites.html">Oblíbené filmy</a>
stranka oblibene filmy nema byt jako dalsi samostatna stranka, vsechny operace a zobrazeni musi byt v ramci jedne stranky index.html. muzete mit napr. jednu stranku se 2 sloupci, levy sloupec bude vyhledavani a pravy sloupec bude seznam oblibenych filmu, po pridani se film ihned zobrazi vpravo...

2021-01-14 20:14 UTC, nvbach91 commented on www/vecs00/sp2/js/main.js
> +        $(".loading").addClass("hide");
loading spinner by se mel skryvat v zavislosti na skonceni volani ajax, a ne po nejake urcite dobe.

2021-01-15 18:42 UTC, vecs00 commented on www/vecs00/sp2/js/main.js
> +        $(".loading").addClass("hide");
Opraveno.

2021-01-15 21:30 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-01-15 21:30 UTC, merged