pfej00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #237
Opened 2020-12-29 19:28 UTC by pfej00

Link: https://investin-app.herokuapp.com/, tohle by měla být oprava, původní branch jsem pro jistotu smazal.

2021-01-22 02:57 UTC, nvbach91 requested changes
- odevzdavejte pouze zdrojove soubory, ne build
- moc to nefunguje, ze by chyba na API?

2021-01-22 02:57 UTC, nvbach91 commented on www/pfej00/sp2/src/Components/Cryptos.js
> +            return crypto.name.toLowerCase().indexOf(this.state.search.toLowerCase()) !== -1;
pouzivejte metodu `includes`

2021-01-22 02:57 UTC, nvbach91 commented on www/pfej00/sp2/src/Components/Cryptos.js
> +      let formulation = <button type="button" className="list-group-item list-group-item-action" onClick = {(e) => {this.saveValueToStorage(e, index)}} >{instrument[0]}</button>;
chybi atribut `key`

2021-01-22 02:57 UTC, nvbach91 commented on www/pfej00/sp2/src/Components/DataError.js
> +            <div class="alert alert-danger" role="alert">{this.props.errorMessage}</div>
className

2021-01-22 02:57 UTC, nvbach91 commented on www/pfej00/sp2/src/Components/Stocks.js
> +      let formulation = <button type="button" className="list-group-item list-group-item-action" onClick = {(e) => {this.saveValueToStorage(e, index)}} >{instrument[1]} - {instrument[2]}</button>;
chybi key prop

2021-01-22 23:48 UTC, nvbach91 requested changes
- vubec to nefunguje, budu potrebovat abyste prisel znovu
- smazte veskere soubory ve slozce build v tomto pull requestu

2021-01-26 16:32 UTC, pfej00 commented
Dobrý den,
 promiňte za zpožděnou zpětnou vazbu, protože jsem teď měl několik zkoušek. Mohu provést nový pull request nebo se domluvíme na další obhajobě, případně jaký termín?
 S pozdravem
Jan Pfeiffer, pfej00

2021-02-05 16:57 UTC, nvbach91 commented
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-02-05 16:57 UTC, nvbach91 approved these changes
![how-to-create-presentation-slides-that-are-out-of-this-world-by-slidecomet-itseugenec-kaixinspeaking-28-638](https://user-images.githubusercontent.com/20724910/104008962-8b66ea80-51aa-11eb-9b47-d64347f9797a.jpg)

2021-02-05 16:57 UTC, merged