apai00-sp2
nvbach91/4IZ268-2020-2021-ZS pull request #241
Opened 2021-01-21 02:26 UTC by apatenko369

https://eso.vse.cz/~apai00/sp2/index.html

2021-01-22 02:07 UTC, nvbach91 commented
tohle jste mel nahrat do puvodniho Pull Requestu tady: https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/195

2021-01-22 02:18 UTC, nvbach91 requested changes
- veskery kod dejte do closure `$(document).ready(() => { ... })`
- neni splnena podminka pouziti API
- neni splnena podminka pouziti browser API (napr. localStorage, location, history, ...)

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +const url = 'https://raw.githubusercontent.com/openfootball/football.json/master/2019-20/en.1.json';
tady bych nerekl ze se jedna o nejakou API

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/index.html
> +                <div class="tooltip">[List of teams]
pouzivejte `<select>`

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/index.html
> +                    <button class="btn button-download" onclick="downloadReport()"><!--<a href="">-->Download<!--</a>--></button>
odstrante ten inline javascript

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +for (let z = 1; z <= copyTextToInput.length; z++) {
pouziva se spis `let i`

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +        teamInput.val($('.info-team-list' + [z]).text());
provedte rovnou submit

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +const buttonMore = (".div-more-information");
apostrof

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/index.html
> +        <script src="./attachment/js/main.js"></script>
script tag se dava nekam jinam

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +        recordTeamList.append(warningMessage);
jeste vycistit ten `<a>` element,

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +    var team1 = [];
const

2021-01-22 02:18 UTC, nvbach91 commented on www/apai00/sp2/attachment/js/main.js
> +                <div id="teamB"> ${outTeamB} :Team2</div>` +
naformatovat, a bez +

2021-01-22 08:36 UTC, apatenko369 commented on www/apai00/sp2/attachment/js/main.js
> +                <div id="teamB"> ${outTeamB} :Team2</div>` +
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/attachment/js/main.js
> +    var team1 = [];
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/attachment/js/main.js
> +        recordTeamList.append(warningMessage);
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/index.html
> +        <script src="./attachment/js/main.js"></script>
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/attachment/js/main.js
> +const buttonMore = (".div-more-information");
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/attachment/js/main.js
> +for (let z = 1; z <= copyTextToInput.length; z++) {
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/index.html
> +                    <button class="btn button-download" onclick="downloadReport()"><!--<a href="">-->Download<!--</a>--></button>
opraveno

2021-01-22 08:37 UTC, apatenko369 commented on www/apai00/sp2/index.html
> +                <div class="tooltip">[List of teams]
opraveno

2021-02-05 12:50 UTC, nvbach91 approved these changes

2021-02-05 12:50 UTC, merged