Sikj01 sp2
nvbach91/4IZ268-2020-2021-ZS pull request #248
Opened 2021-01-28 17:51 UTC by sikj01

odevzdávám momentální podobu

2021-01-28 23:20 UTC, nvbach91 commented
tenhle Pull Request smazte a nahrajte POUZE druhou semestralku (podle navodu) do stavajiciho Pull Requestu zde: https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/231

2021-01-28 23:24 UTC, nvbach91 requested changes

2021-01-28 23:24 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +        $("#main").html(`
elementy z HTML vybirejte predem, ne behem pouziti

2021-01-28 23:24 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +    function pageSearch() {
lepsi nazev funkce (renderSearchPage)

2021-01-28 23:24 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +            pageWatchlist()
napodobne

2021-01-28 23:24 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +                    <tbody id="tableContent"></tbody>
nepouzivejte table, ale div

2021-01-28 23:24 UTC, nvbach91 commented on www/sikj01/sp2/js/script.js
> +                    moviesGenres = result.results;
tohle volani je tady k nicemu

2021-01-29 00:07 UTC, sikj01 commented
Dobrý večer,
já jsem omylem uzavřel ten správný pull-request.

J.S.

Stáhněte si Outlook pro Android<https://aka.ms/ghei36>

________________________________
From: Nguyen Viet Bach <notifications@github.com>
Sent: Friday, January 29, 2021 12:25:08 AM
To: nvbach91/4IZ268-2020-2021-ZS <4IZ268-2020-2021-ZS@noreply.github.com>
Cc: Jan Sikora <sikj01@vse.cz>; Author <author@noreply.github.com>
Subject: Re: [nvbach91/4IZ268-2020-2021-ZS] Sikj01 sp2 (#248)


@nvbach91 requested changes on this pull request.

________________________________

In www/sikj01/sp2/js/script.js<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#discussion_r566474528>:

> @@ -0,0 +1,148 @@
+$(document).ready(() => {
+    console.log("funguju");
+
+    // RENDER WATCHLIST
+    function pageWatchlist() {
+        $("#main").html(`


elementy z HTML vybirejte predem, ne behem pouziti

________________________________

In www/sikj01/sp2/js/script.js<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#discussion_r566474702>:

> +                            <th scope="col">Genres</th>
+                            <th scope="col">Personal score</th>
+                            <th scope="col">Delete movie</th>
+                        </tr>
+                    </thead>
+                    <tbody id="tableContent"></tbody>
+                </table>
+            </section>`)
+
+        $("#moveToSearch").click(function () {
+            pageSearch()
+        });
+
+    }
+
+    function pageSearch() {


lepsi nazev funkce (renderSearchPage)

________________________________

In www/sikj01/sp2/js/script.js<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#discussion_r566474875>:

> +                <table class="table table-striped table-dark table-bordered">
+                    <thead>
+                        <tr>
+                            <th scope="col">Name</th>
+                            <th scope="col">Release date</th>
+                            <th scope="col">Genres</th>
+                            <th scope="col">User score</th>
+                            <th scope="col">Add movie</th>
+                        </tr>
+                    </thead>
+                    <tbody id="tableContent"></tbody>
+                </table>
+            </section>`)
+
+        $("#moveToWatchlist").click(function () {
+            pageWatchlist()


napodobne

________________________________

In www/sikj01/sp2/js/script.js<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#discussion_r566474973>:

> +                        </button>
+                    </div>
+                </div>
+            </nav>
+            <section class="row">
+                <table class="table table-striped table-dark table-bordered">
+                    <thead>
+                        <tr>
+                            <th scope="col">Name</th>
+                            <th scope="col">Release date</th>
+                            <th scope="col">Genres</th>
+                            <th scope="col">User score</th>
+                            <th scope="col">Add movie</th>
+                        </tr>
+                    </thead>
+                    <tbody id="tableContent"></tbody>


nepouzivejte table, ale div

________________________________

In www/sikj01/sp2/js/script.js<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#discussion_r566475922>:

> +            $("#tableContent").html(`<tr><td colspan="7">Search for movie</td></tr>`);
+        }
+    }
+
+    // getting genres from genres_ids
+    function getMovieGenre(result) {
+        var moviesGenres
+        var results = "";
+
+        if (!moviesGenres) {
+            $.ajax({
+                url: `https://api.themoviedb.org/3/genre/movie/list?api_key=a0c2b64a6fafee6976844c7c2cf29a7a&language=en-US`,
+                success: function (result) {
+                    console.log(result)
+
+                    moviesGenres = result.results;


tohle volani je tady k nicemu

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/248#pullrequestreview-578823977>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ARHHKSSBHN4PKKPJSS7ECLLS4HW5JANCNFSM4WXPAZDQ>.

2021-01-29 21:17 UTC, nvbach91 commented
https://github.com/nvbach91/4IZ268-2020-2021-ZS/pull/231

2021-02-02 13:08 UTC, closed without merging