valm08-hw08
nvbach91/4IZ268-2020-2021-ZS pull request #47
Opened 2020-11-13 19:04 UTC by valm08

Odevzdávám DÚ č. 8. 
https://eso.vse.cz/~valm08/hw08/

2020-11-16 18:16 UTC, nvbach91 requested changes
Prilis moc chyb:
- deklarace promennych
- pojmenovani funkci a promennych
- formatovani kodu
- stredniky

a proto to neni moc awesome

2020-11-16 18:23 UTC, valm08 commented
Můžete to rozvést? Nerozumím problému s deklarací proměnných.

2020-11-16 18:51 UTC, nvbach91 requested changes

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +    C = (F - 32)/9*5;
chybi let nebo const

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +    age = year - birth
chybi let nebo const, a strednik

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +    c = a/b;
chybi let nebo const

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +    for (i = 13; i <= 730; i = i + 13) {
chybi let

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +function area (r) {
calculateCircleArea

2020-11-16 18:51 UTC, nvbach91 commented on www/valm08/hw08/homework.js
> +function triangle (a, b, c) {
isTriangle

2020-11-18 13:36 UTC, nvbach91 approved these changes

2020-11-18 13:37 UTC, merged