novd35-hw08
nvbach91/4IZ268-2020-2021-ZS pull request #76
Opened 2020-11-19 19:33 UTC by dnovosad1

Odevzdávám domácí úkol 8 
https://eso.vse.cz/~novd35/hw08/index.html
https://eso.vse.cz/~novd35/hw08/main.js

2020-11-20 00:25 UTC, nvbach91 requested changes

2020-11-20 00:25 UTC, nvbach91 commented on www/novd35/hw08/index.html
> +<script src="main.js"></script>
musite psat validni HTML

2020-11-20 00:25 UTC, nvbach91 commented on www/novd35/hw08/main.js
> +printAge = date_of_birth => console.log('3)' + 'Pepovi je ' + (year - date_of_birth) + ' let.');
chybi deklarace var / let / const

2020-11-20 00:25 UTC, nvbach91 commented on www/novd35/hw08/main.js
> +isItTriangle = (a, b, c) => {
`const isTriangle`

2020-11-20 11:04 UTC, dnovosad1 commented
Přidal jsem commit s opravou úkolu. Nevím, zda to mám vždy zmiňovat( v postupu se o tom nepsalo).
 @nvbach91

2020-11-24 16:49 UTC, nvbach91 approved these changes

2020-11-24 16:50 UTC, merged