valm08-hw09
nvbach91/4IZ268-2020-2021-ZS pull request #88
Opened 2020-11-21 18:32 UTC by valm08

Odevzdávám DÚ č. 9 https://eso.vse.cz/~valm08/hw09/

Manipulace s DOMem by měla být správná, ale nedovedu implementovat Caesarovu šifru. Nevím, kde je problém.

PS: odpovíte mi prosím na issue „Vyhodnocení SP1“ ať mohu začít s opravou? Děkuji.

2020-11-26 22:48 UTC, nvbach91 requested changes

2020-11-26 22:48 UTC, nvbach91 commented on www/valm08/hw09/js/main.js
> +const decipherButton = document.getElementById("decipher");
lepsi pouzit querySelector

2020-11-26 22:48 UTC, nvbach91 commented on www/valm08/hw09/js/main.js
> +console.log(shiftChar("A", 1));
myslim ze vysledek `shiftChar('A', 1)` by mel byt `Z` a ne `Y`

2020-11-26 22:48 UTC, nvbach91 commented on www/valm08/hw09/js/main.js
> +    document.getElementById("output").innerText = shiftString(cipherText, usedKey);
veskere elementy by se mely vybirat jednou pred pouzitim, takze neco jako ten Vas decipherButton

2020-12-03 12:31 UTC, nvbach91 commented
@valm08 budete to opravovat?

2020-12-03 14:45 UTC, valm08 commented
Ne, ani v opačném směru mi to nefungovalo (viz zakomentovaný kód).

2020-12-03 15:37 UTC, nvbach91 commented
Však ve funkci shiftChar jste se jenom netrefil o jednu pozici

2020-12-06 16:58 UTC, closed without merging